Petpal-frontend/petpal-frontend

petpal/src/components/Walk/WalkItem.jsx
petpal/src/components/Walk/WalkItemStyle.jsx
petpal/src/styles/GlobalStyle.jsx

Refact: Refactoring InfoGroup width

:memo: Refact: Refactoring InfoGroup width

---

petpal/src/components/Slider/Slider.jsx

:memo: Feater: SliderModify

---

petpal/src/api/axiosInstance.js
petpal/src/api/interseptor.js
petpal/src/api/signUpApi.js
petpal/src/components/SignUp/SignUp.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

Feat: Separate APIs from Signup component

:sparkles: Feat: Separate APIs from Signup component

---

petpal/src/components/Common/ImageButtonStyle.jsx
petpal/src/components/Common/InfinityScroll/InfinityScroll.jsx
petpal/src/components/Common/NavBar/NavBar.jsx
petpal/src/components/Common/NavBar/NavBarStyle.jsx
petpal/src/components/HomeHeader/HomeHeaderLogo.jsx
petpal/src/components/HomeHeader/HomeHeaderLogoStyle.jsx
petpal/src/components/HomeHeader/HomeHeaderStyle.jsx
petpal/src/components/Product/ProductList.jsx
petpal/src/components/Product/ProductListStyle.jsx
petpal/src/components/SearchBar/SearchBarStyle.jsx
petpal/src/components/Slider/SliderStyle.jsx
petpal/src/components/Walk/WalkItemStyle.jsx
petpal/src/pages/HomePage/HomePage.jsx
petpal/src/pages/Router.jsx
petpal/src/styles/GlobalStyle.jsx

GlobalStyle, Home Layout modify and NavBar

💄 GlobalStyle, Home Layout modify and NavBar

---

petpal/src/components/Common/Button/FormButton/FormButtonStyle.jsx
petpal/src/components/SignUp/SignUp.jsx
petpal/src/components/Walk/WalkDetailItem.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

:bug: Fix: Fixed merge conflict

---

petpal/src/pages/FollowPage/FollowerPage.jsx

:sparkles: Feat: follow

---

petpal/src/components/Common/NavBar/BottomButtonContainer.jsx
petpal/src/components/Common/NavBar/BottomButtonContainerStyle.jsx
petpal/src/components/Common/NavBar/BottomModal.jsx
petpal/src/components/Common/NavBar/BottomModalStyle.jsx
petpal/src/components/Common/NavBar/NavBar.jsx
petpal/src/components/Common/NavBar/NavBarStyle.jsx

:lipstick: Bottommodal

---

petpal/src/components/Common/Header/Header.jsx

:bug: Fix: import error fixed

---

petpal/src/api/productListApi.js
petpal/src/components/Product/ProductList.jsx
petpal/src/components/Product/ProductListStyle.jsx

:sparkles: Feat: ProductList API

---

petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/pages/CarePage/CareDetailPage.jsx

Fix: CareDetail input data fixed

:bug: Fix: CareDetail input data fixed

---

petpal/src/api/commentApi.js
petpal/src/components/Common/Comment/Comment.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

:sparkles: Feat: Comment API

---

petpal/src/api/commentApi.js
petpal/src/api/walk.js
petpal/src/components/Common/Comment/Comment.jsx
petpal/src/components/Common/Comment/CommentStyle.jsx
petpal/src/components/Common/Header/Header.jsx
petpal/src/components/Common/Header/HeaderStyle.jsx
petpal/src/components/Common/Input/BottomInput/BottomInputStyle.jsx
petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/components/Common/SpanImg/SpanImgStyle.jsx
petpal/src/components/Common/Userinfo/UserInfoStyle.jsx
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Walk/WalkDetailItem.jsx
petpal/src/components/Walk/WalkDetailItemStyle.jsx
petpal/src/components/Walk/WalkItemList.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx
petpal/src/styles/GlobalStyle.jsx

✨Feat: Comment 삭제 API 연결

---

petpal/src/api/axiosInstance.js
petpal/src/api/follow.js
petpal/src/api/searchApi.js
petpal/src/components/Follow/FollowItem.jsx
petpal/src/components/Follow/FollowItemStyle.jsx
petpal/src/components/Follow/FollowerList.jsx
petpal/src/components/Follow/FollowerListStyle.jsx
petpal/src/components/Product/ProductPost.jsx
petpal/src/components/Product/ProductPostStyle.jsx
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Search/Search.jsx
petpal/src/components/Search/SearchStyle.jsx
petpal/src/pages/FollowPage/FollowerPage.jsx
petpal/src/pages/Router.jsx
petpal/src/pages/SearchPage/SearchPage.jsx

✨ Feat: FollowPage, Follow API

✨ Feat: FollowPage, Follow API

---

petpal/src/api/axiosInstance.js
petpal/src/api/searchApi.js
petpal/src/components/Product/ProductPost.jsx
petpal/src/components/Product/ProductPostStyle.jsx
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Search/Search.jsx
petpal/src/components/Search/SearchStyle.jsx
petpal/src/pages/Router.jsx
petpal/src/pages/SearchPage/SearchPage.jsx

Feat: Search API & Router, ProductPost 이미지 위치 수정

Feat: Search API & Router, ProductPost 이미지 위치 수정

---

petpal/src/components/Product/ProductList.jsx
petpal/src/components/Product/ProductListStyle.jsx

:lipstick: Edit: productlist ui

---

petpal/src/pages/ProfilePage/ProfilePage.jsx
petpal/src/styles/GlobalStyle.jsx

:lipstick: Ui: overflow-y:auto

---

petpal/src/pages/CarePage/CareDetailPage.jsx
petpal/src/styles/GlobalStyle.jsx

:lipstick: Ui: globalstyle edit

---

petpal/src/components/Product/ProductPost.jsx
petpal/src/pages/ProductPage/ProductDetailPage.jsx
petpal/src/pages/ProductPage/ProductEditPage.jsx

:bug: Fix: product previewimage

---

petpal/src/components/Profile/ProfileEditForm.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

:bug: Fix: profileedit

---

petpal/src/components/Common/Header/Header.jsx
petpal/src/components/Walk/WalkItem.jsx
petpal/src/components/Walk/WalkItemList.jsx
petpal/src/pages/WalkPage/WalkListPage.jsx

Style: Header text-align center

:art: Style: Header text-align center

---

petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Profile/MyProfileStyle.jsx
petpal/src/components/Profile/YourProfile.jsx

:bug: Fix: profile post image fixed

---

petpal/src/components/Common/Post/Post.jsx
petpal/src/components/Common/Post/PostEdit.jsx
petpal/src/pages/WalkPage/WalkEditPage.jsx

:recycle: Refactor: postEdit

---

petpal/src/api/profile.js
petpal/src/components/Common/Modal/useAlertControlStyle.jsx
petpal/src/components/Product/ProductDetail.jsx
petpal/src/pages/ProfilePage/YourProfilePage.jsx
petpal/src/pages/Router.jsx

:sparkles: Feat: your profile page API

---

petpal/src/api/care.js
petpal/src/api/walk.js
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Profile/MyProfileStyle.jsx
petpal/src/components/Profile/YourProfile.jsx
petpal/src/pages/ProfilePage/YourProfilePage.jsx

:recycle: Refactor:profile setting

---

petpal/src/components/HomeHeader/HomeHeaderLogoStyle.jsx
petpal/src/components/HomeHeader/HomeHeaderStyle.jsx
petpal/src/components/Search/Search.jsx
petpal/src/pages/HomePage/HomePage.jsx

Style: Home search button modify

:art: Style: Home search button modify

---

petpal/src/api/commentApi.js
petpal/src/components/Common/Comment/Comment.jsx
petpal/src/components/Common/Input/BottomInput/BottomInput.jsx
petpal/src/components/Common/Input/BottomInput/BottomInputStyle.jsx
petpal/src/components/Common/Modal/useAlertControlStyle.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

♻️ Refactor: Comment Delete, Report 리팩토링

---

petpal/src/components/Care/CareItemList.jsx
petpal/src/components/Walk/WalkItemList.jsx

:lipstick: Ui: add link to postbutton

---

petpal/src/components/Search/Search.jsx

Refactor: search button connect to profile

:recycle: Refactor: search button connect to profile

---

petpal/src/components/Chat/ChatRoom.jsx
petpal/src/components/Common/Comment/Comment.jsx
petpal/src/pages/CarePage/CareDetailPage.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

🐛 Fix: Comment 등록 오류 수정

---

petpal/src/components/SignUp/SignUp.jsx

Fix: signup image upload error fixed

:bug: Fix: signup image upload error fixed

---

petpal/src/components/SignUp/SignUp.jsx

:bug: Fix: signup img prev fixed

---

petpal/src/components/Profile/ProfileEditForm.jsx

:ambulance: Fix: editprofle

---

petpal/src/components/Care/CareItemStyle.jsx
petpal/src/components/Product/ProductPost.jsx
petpal/src/components/Walk/WalkItemStyle.jsx

:lipstick: Style: editui

---

petpal/src/components/Walk/WalkDetailItem.jsx

Feat: Link the userInfo of Post to yourProfile

:sparkles: Feat: Link the userInfo of Post to yourProfile

---

petpal/src/pages/ProfilePage/ProfilePage.jsx

:ambulance: Fix: loginbug

---

petpal/src/components/Common/Post/PostEdit.jsx
petpal/src/components/Profile/MyProfile.jsx

:sparkles: Feat: add Link

---

petpal/src/components/Common/Comment/Comment.jsx
petpal/src/components/Walk/WalkDetailItem.jsx

Feat: Link the userInfo of Comments

:sparkles: Feat: Link the userInfo of Comments

---

petpal/src/components/Common/Post/PostEdit.jsx
petpal/src/components/Follow/FollowItem.jsx

:bug: Fix: fix follow profile link

---

petpal/src/components/Profile/MyProfileStyle.jsx
petpal/src/components/Profile/YourProfile.jsx

Feat: add a Link to YourProfile Page

:sparkles: Feat: add a Link to YourProfile Page

---

petpal/src/components/Profile/ProfileEditForm.jsx
petpal/src/components/SignUp/SignUpStyle.jsx

:bug: Fix: profileimage

---

petpal/src/components/Profile/ProfileEditForm.jsx

:bug: Fix: get userState

---

petpal/src/components/Follow/FollowItem.jsx
petpal/src/components/Follow/FollowList.jsx
petpal/src/components/Profile/YourProfile.jsx

Fix: follow btns on myProfile removed

:bug: Fix: follow btns on myProfile removed

---

petpal/src/components/Chat/ChatList.jsx
petpal/src/components/Chat/ChatListStyle.jsx
petpal/src/components/Chat/ChatRoom.jsx
petpal/src/components/Chat/ChatRoomStyle.jsx
petpal/src/components/Common/Header/Header.jsx
petpal/src/components/Common/Input/BottomInput/BottomInput.jsx
petpal/src/components/Profile/ProfileEditForm.jsx
petpal/src/mock/dummyChat.js
petpal/src/pages/CarePage/CareDetailPage.jsx
petpal/src/pages/ChatPage/ChatRoomPage.jsx
petpal/src/pages/Router.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

ChatList, ChatRoom 텍스트 입력 및 이미지 업로드 기능 추가

:sparkles: Feat: ChatList, ChatRoom 텍스트 입력 및 이미지 업로드 기능 추가

---

petpal/src/pages/Router.jsx

페이지 이동 시,이전 페이지 스크롤 위치를 보여주는 문제 해결

:sparkles: Feat: scrollToTop

---

petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/components/Product/ProductDetail.jsx
petpal/src/components/Product/ProductList.jsx
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Profile/YourProfile.jsx

:lipstick: Style: 한국금액표기법 적용

---

petpal/src/components/Common/Post/Post.jsx
petpal/src/components/Product/ProductPost.jsx
petpal/src/pages/ProductPage/ProductEditPage.jsx
petpal/src/pages/Router.jsx

Fix: 상품수정화면: 미리보기 에러 수정, 
새로운 이미지 등록안하고 업로드시에 빈값 들어갔던거 수정,
input값 비어있으면 필수값으로 입력하도록 alert추가

:bug: Fix: 상품수정화면: 미리보기 에러 수정, input값 비어있으면 필수값으로 입력하도록 alert추가

---

petpal/src/components/Walk/WalkDetailItem.jsx
petpal/src/pages/CarePage/CareDetailPage.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx

Fix: Post detail pages comment num fixed

:bug: Fix: Post detail pages comment num fixed

---

petpal/src/api/feedApi.js
petpal/src/api/searchApi.js
petpal/src/components/Common/InfinityScroll/scroll.jsx
petpal/src/components/Common/InfinityScroll/scrollStyle.jsx
petpal/src/components/Follow/FollowItem.jsx
petpal/src/pages/FeedPage/FeedPage.jsx
petpal/src/pages/HomePage/HomePage.jsx

Feat: FeedPage, HomePage API and scroll modify

:sparkles: Feat: FeedPage, HomePage API and scroll modify

---

petpal/src/components/Common/Header/Header.jsx

:bug: Fix: header switch case fixed

---

petpal/src/components/Chat/ChatRoom.jsx
petpal/src/components/Chat/ChatRoomStyle.jsx
petpal/src/components/Common/InfinityScroll/scrollStyle.jsx
petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/components/Slider/SliderStyle.jsx
petpal/src/mock/dummyChat.js
petpal/src/pages/ChatPage/ChatRoomPage.jsx

:art: Style: Post List & Home Style 수정

---

petpal/src/components/Chat/ChatList.jsx
petpal/src/components/Common/Header/HeaderStyle.jsx
petpal/src/components/Common/InfinityScroll/scrollStyle.jsx
petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/mock/dummyChat.js
petpal/src/pages/ChatPage/ChatRoomPage.jsx
petpal/src/pages/Router.jsx

:art: Style: Header width 값 수정

---

petpal/src/components/Common/Button/SubmitButton/Button.jsx
petpal/src/components/Common/Header/Header.jsx
petpal/src/components/Product/ProductDetail.jsx
petpal/src/components/Walk/WalkDetailItem.jsx
petpal/src/pages/ChatPage/ChatRoomPage.jsx

:sparkles: Feat: user chatconnect

---

petpal/src/components/Chat/ChatList.jsx
petpal/src/components/Chat/ChatListStyle.jsx
petpal/src/components/Chat/ChatRoom.jsx
petpal/src/components/Chat/ChatRoomStyle.jsx
petpal/src/mock/dummyChat.js
petpal/src/pages/ChatPage/ChatListPage.jsx
petpal/src/pages/ChatPage/ChatRoomPage.jsx
petpal/src/pages/Router.jsx
petpal/src/styles/GlobalStyle.jsx

:recycle: Refactor: ChatRoom 말풍선 분리되게 수정

---

petpal/src/pages/ChatPage/ChatRoomPage.jsx

:recycle: Refactor: ChatRoom 불필요한 코드 주석 처리

---

petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/components/Follow/FollowButton.jsx
petpal/src/components/Walk/WalkDetailItem.jsx

Fix: Component padding fixed and Follow button on my info fixed

:bug: Fix: Component padding fixed and Follow button on my info fixed

---

petpal/src/components/Common/InfinityScroll/scrollStyle.jsx
petpal/src/styles/GlobalStyle.jsx

Fix: feed image size fixed and min-height resetting

:bug: Fix: feed image size fixed and min-height resetting

---

petpal/src/components/Common/InfinityScroll/scrollStyle.jsx
petpal/src/pages/WalkPage/WalkListPage.jsx

Style: scrollUi, walklist dumydata filter

:lipstick: Style: scrollUi, datafilter

---

petpal/src/api/axiosInstance.js
petpal/src/components/Care/CareItem.jsx
petpal/src/components/Common/Comment/Comment.jsx
petpal/src/components/Common/InfinityScroll/scroll.jsx
petpal/src/components/Common/InfinityScroll/scrollTemp.jsx
petpal/src/components/Common/Post/Post.jsx
petpal/src/components/Common/Post/PostEdit.jsx
petpal/src/components/Follow/FollowButton.jsx
petpal/src/components/Profile/MyProfile.jsx
petpal/src/components/Profile/ProfileEditForm.jsx
petpal/src/components/Profile/YourProfile.jsx
petpal/src/components/SignUp/SignUp.jsx
petpal/src/components/Walk/WalkDetailItem.jsx
petpal/src/components/Walk/WalkItem.jsx
petpal/src/pages/CarePage/CareEditPage.jsx
petpal/src/pages/CarePage/CareListPage.jsx
petpal/src/pages/ChatPage/ChatRoomPage.jsx
petpal/src/pages/FeedPage/FeedPage.jsx
petpal/src/pages/HomePage/HomePage.jsx
petpal/src/pages/LoginPage/LoginPage.jsx
petpal/src/pages/ProductPage/ProductEditPage.jsx
petpal/src/pages/ProductPage/ProductPostPage.jsx
petpal/src/pages/ProfilePage/ProfileEditPage.jsx
petpal/src/pages/ProfilePage/YourProfilePage.jsx
petpal/src/pages/WalkPage/WalkDetailPage.jsx
petpal/src/pages/WalkPage/WalkEditPage.jsx
petpal/src/pages/WalkPage/WalkListPage.jsx

Add: console annotation and handle warnning

:memo: Add: console annotation and handle warnning

---

petpal/src/components/Common/Layout/LayoutStyle.jsx
petpal/src/components/Product/ProductDetail.jsx
petpal/src/components/Product/ProductDetailStyle.jsx
petpal/src/pages/Router.jsx

Style: chatting btn on Product Detail modify

:art: Style: chatting btn on Product Detail modify

---

src/pages/ProfilePage/ProfilePage.jsx

:memo: AddDoc: add profilepage console

---

src/components/Common/Modal/useModalControlStyle.jsx
src/components/Profile/MyProfileStyle.jsx
src/components/Splash/SplashStyle.jsx
src/styles/GlobalStyle.jsx

- Modal Layout on mobile fixed
- Profile : Styled user image border

:bug: Fix: Modal Layout on mobile fixed

---

src/components/Chat/ChatList.jsx
src/components/Chat/ChatRoom.jsx
src/components/Common/Layout/LayoutStyle.jsx
src/components/Search/Search.jsx
src/components/SearchBar/SearchBarStyle.jsx
src/mock/dummyChat.js

Style: Search Bar 넓이, focus 스타일 수정

:art: Style: Search Bar 넓이, focus 스타일 수정

---

src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPageStyle.jsx

Fix: login layout fixed on mobile

:bug: Fix: login layout fixed on mobile

---

src/components/Common/Comment/Comment.jsx
src/pages/CarePage/CareDetailPage.jsx

:bug: Fix: Comment 취소 및 삭제 오류 수정

---

src/assets/image/i-icon.svg
src/components/Common/Header/Header.jsx
src/components/Common/Tooltip/ToolStyle.jsx

:lipstick: Style: tooltip

---

README.md

:memo: Update: README.md Updated

---

src/styles/GlobalStyle.jsx
src/styles/font.css

:art: Style: Font 수정

---

src/components/SignUp/SignUp.jsx

:bug: Fix: run err fixed

---

src/components/Slider/SliderStyle.jsx

:lipstick: Style: sliderUi

---

src/components/Chat/ChatRoomStyle.jsx
src/components/Product/ProductPostStyle.jsx
src/styles/GlobalStyle.jsx

:sparkles: Feat: font

---

src/components/SignUp/SignUp.jsx

:bug: Fix: signUp layout fixed

---

src/components/Product/ProductListStyle.jsx

글쓰기 버튼 레이아웃 수정
- 버튼 레이아웃 수정
Close: #167

:recycle: Refactor: 글쓰기 버튼 레이아웃 수정

---

src/components/Care/CareItemList.jsx
src/components/Common/Button/WriteButton/WriteButton.jsx
src/components/Common/Button/WriteButton/WriteButtonStyle.jsx
src/components/Product/ProductList.jsx
src/components/Product/ProductListStyle.jsx
src/components/Walk/WalkItemList.jsx

글쓰기 버튼 컴포넌트 생성
- 글쓰기 버튼 컴포넌트로 분리
- 연결된 파일 수정
Close: #169

:recycle: Refactor: 글쓰기 버튼 컴포넌트 생성

---

src/api/product.js
src/api/productListApi.js
src/components/Care/CareItemList.jsx
src/components/Common/Button/WriteButton/WriteButton.jsx
src/components/Common/Button/WriteButton/WriteButtonStyle.jsx
src/components/Product/ProductList.jsx
src/components/Product/ProductListStyle.jsx
src/components/Walk/WalkItemList.jsx

상품 리스트 API 수정
- limit 숫자 수정
- productListApi.js 코드를 product.js로 이동 후 삭제
- 연결된 파일 수정
Close: #171

♻️ Refactor: 상품 리스트 API 수정

---

src/components/Common/Comment/CommentStyle.jsx
src/pages/CarePage/CareDetailPage.jsx
src/pages/WalkPage/WalkDetailPage.jsx

:recycle: Refactor: commentFocus

---

src/components/AddressSearch/AddressSearch.jsx
src/components/AddressSearch/AddressSearchEdit.jsx

모달 레이아웃 수정
- 모달 너비 수정
Close: #179

:recycle: Refactor: 모달 레이아웃 수정

---

src/components/AddressSearch/AddressSearch.jsx
src/components/AddressSearch/AddressSearchEdit.jsx
src/hooks/useDebounce.js
src/pages/SearchPage/SearchPage.jsx

검색에 debounce 기능 추가
- debounce를 적용해 입력할 때마다 검색 결과를 보여주지 않고, 마지막 입력 후 일정 시간이 지난 뒤에 검색 결과를 보여주도록 수정
Close: #183

✨ Feat: 검색 debounce 적용

---

src/assets/image/icon-checkbox-fill.svg
src/assets/image/icon-checkbox.svg
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPageStyle.jsx

로그인 페이지에 체험하기 체크박스 기능 추가
- 체험하기 체크박스 추가
- 체크박스를 클릭하면 이메일, 비밀번호가 입력되도록 구현
Close: #191

:sparkles: Feat: 로그인 페이지에 체험하기 체크박스 기능 추가

---

src/assets/image/icon-checkbox-fill.svg
src/assets/image/icon-checkbox.svg
src/components/Product/ProductDetailStyle.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPageStyle.jsx

상품 상세 페이지 UI 수정
- UI 수정
Close: #193

🎨 Style: 상품 상세 페이지 UI 수정

---

src/pages/CarePage/CareDetailPage.jsx
src/pages/WalkPage/WalkDetailPage.jsx

산책, 돌보미 상세페이지에 들어가게 되면 아래로 내려간 화면이 보였던 것 수정

:pencil2: Fix: commentFocus

---

src/components/Common/Header/Header.jsx
src/components/Common/Tooltip/ToolStyle.jsx

tooltip UI 수정
- tooltip UI 수정, 리팩토링
- tooltip 텍스트 수정
Close: #197

♻️ Refactor: tooltip UI 수정, 리팩토링

---

src/components/Common/Header/Header.jsx

:bug: Fix: eslint error

---

src/components/Common/InfinityScroll/scroll.jsx
src/components/Common/InfinityScroll/scrollStyle.jsx
src/components/WalkAndCare/PostListItemStyle.jsx
src/pages/CarePage/CareListPage.jsx
src/pages/WalkPage/WalkListPage.jsx

로딩중, 피드 게시물 작성 유도 화면 겹쳐 보이는 문제 해결

🐛 Bug: 로딩중, 피드 게시물 작성 유도 화면 겹쳐 보이는 문제 해결

---

README.md
src/components/Common/InfinityScroll/scroll.jsx

dev 리드미 수정

---

src/pages/CarePage/CareListPage.jsx
src/pages/WalkPage/WalkListPage.jsx

:bug: Fix: 로딩중 화면 겹쳐 보이는 문제 수정
